stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/your-username/devops-metrics-monitoring:latest

# Run unit tests
test:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest -v

# Build and push Docker image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

# Deploy to Kubernetes
deploy:
  stage: deploy
  image: alpine/helm:3.12.0
  before_script:
    - apk add --no-cache aws-cli kubectl
    - echo $KUBE_CONFIG | base64 -d > kubeconfig
    - export KUBECONFIG=kubeconfig
  script:
    - aws eks update-kubeconfig --name metrics-cluster --region us-east-1
    - kubectl apply -f k8s/